<?php


/**
 * Implements hook_menu_alter().
 */
function hc_user_menu_alter(&$items) {

  $items['user']['type'] = MENU_CALLBACK;
  $items['user/register']['type'] = MENU_CALLBACK;
  $items['user/password']['type'] = MENU_CALLBACK;
}

/**
 * Implements hook_form_alter
 */
function hc_user_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_login') {
    $form['name']['#prefix']  = '<div id="' . $form_id . '_form">';
    $form['name']['#prefix'] .= '<h1>' . t('Login') . '</h1>';
    $form['pass']['#suffix'] = l(t('Forgot your password?'), 'user/password', array('attributes' => array('class' => 'login-password', 'title' => t('Get a new password'))));
    $form['actions']['#suffix']  = '</div>';
    $form['actions']['#suffix'] .= '<div class="create-account clearfix">';
    $form['actions']['#suffix'] .= "\r<h2>" . t('I don\'t have an account') . "</h2>";
    $form['actions']['#suffix'] .= "\r" . l(t('Create an account'), 'user/register', array('attributes' => array('class' => 'login-register', 'title' => t('Create a new account'))));
    $form['actions']['#suffix'] .= '</div>';
  }
  if ($form_id == 'user_pass') {
    $form['name']['#prefix'] = '<div id="' . $form_id . '_form">';
    $form['name']['#prefix'] .= '<h1>' . t('Request a new password') . '</h1>';
    $form['actions']['#suffix'] = '<div class="back-to-login clearfix">' . l(t('Back to login'), 'user/login', array('attributes' => array('class' => 'login-account', 'title' => t('Sign in')))) . '</div>';
    $form['actions']['#suffix'] .= '</div>';
  }
  if ($form_id == 'user_register_form') {
    // "registration info" block
    $block = block_load('block', '11');
    $render_array = _block_get_renderable_array(_block_render_blocks(array($block)));
    $output = render($render_array);
  
    $form['account']['name']['#prefix'] = '<div id="' . $form_id . '">';
    $form['account']['name']['#prefix'] .= '<h1>' . t('Register') . '</h1>';
    // block
    $form['account']['name']['#prefix'] .= $output;
    
    $form['actions']['submit']['#suffix'] = '</div>';
    $form['actions']['submit']['#suffix'] .= '<div class="back-to-login">' . l(t('Back to login'), 'user/login', array('attributes' => array('class' => 'login-account', 'title' => t('Sign in')))) . '</div>';    
  }
  
	if ($form_id == 'user_profile_form') {
    $form['mimemail']['#access'] = FALSE;	  
	}
  
}

/**
 * Implements hook_user_view_alter().
 *
 * Hide other infos.
 */
function hc_user_user_view_alter(&$build) {
  if (isset($build['mimemail'])) {
    unset($build['mimemail']);
  }
  if (isset($build['summary'])) {
    unset($build['summary']);
  }
}

/**
 * Implements hook_preprocess_page().
 */
function hc_user_preprocess_page(&$variables) {
  switch (current_path()) {
    case 'user':
    case 'user/login':
    case 'user/register':
    case 'user/password':
      $variables['title'] = '';
  }
}
